
# memory settings
shared_buffers=512MB
effective_cache_size=1GB
work_mem=16MB
maintenance_work_mem=256MB

#connection settings
max_connection=20

#WAL settings
synchronous_commit=off
wal_buffers=64MB
checkpoint_completion_target=0.9
checkpoint_timeout=10min
max_wal_size=2GB

#Performance
random_page_cost=1.1
seq_page_cost=1.0
effective_io_concurrency=200

# #Autovacuum (will need this for update experiments)
# autovacuum=off
# autovacuum_vacuum_scale_factor=0.05
# autovacuum_analyze_scale_factor=0.02

# #logging
# log_min_duration_statement=100
# log_checkpoints=on
# log_connections=off
# log_lock_waits=on
# track_io_timing=on
# track_counts=on
